const productsTypes = {
	FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
	SET_PRODUCTS: 'SET_PRODUCTS',
	FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
	SET_PRODUCT: 'SET_PRODUCT',
	RESET_PRODUCT: 'RESET_PRODUCT',
	ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
	DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
	EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
	PRODUCT_ERROR: 'PRODUCT_ERROR',
	RESET_PRODUCT_ERROR: 'RESET_PRODUCT_ERROR'
};

export default productsTypes;
