const userTypes = {
	SIGN_IN_START: 'SIGN_IN_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
	SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
	USER_ERROR: 'USER_ERROR',
	RESET_USER_ERROR: 'RESET_USER_ERROR'
};

export default userTypes;
